defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

n_workers: 24

preprocessing:
  active: False
  input_file: /home/sebalzer/Documents/Projects/ATTRAS_Amyloidose/Data/4D/filtered_phases_Out_MyoCa.csv
  label_file: /home/sebalzer/Documents/Projects/ATTRAS_Amyloidose/Data/ATTRAS_TAVI_Redcap_ID.xlsx

time_series:
  test_size: 0.3
  seed: 42
  scoring: 'roc_auc'
  corr_threshold: 0.95
  trafos:
    None: True
    PCA: True
  trafo_params:
    None: {}
    PCA:
      trafo___n_components: [1, 2, 3]
  models:
    KNN: True
    arsenal: True
    rocket: True
    SVC: True
    forest: True
    catch22: True
    tsfresh: False
    random_interval: True
    CNN: True
    CNTC: False
    FCN: True
    LSTMFCN: True
    MACNN: True
    MCDCNN: True
    MLP: True
    ResNet: True
    SimpleRNN: True
    TapNet: True
  model_params:
    KNN:
      kneighbours___n_neighbors: [3, 5, 7]
    arsenal:
      arsenal___n_estimators: [100, 200, 300]
    rocket:
      rocket___n_kernels: [100, 200, 300]
    SVC:
      svc___C: [0.1, 1, 10]
      svc___gamma: [0.1, 1, 10]
    forest:
      randomforestclassifier___n_estimators: [100, 200]
      randomforestclassifier___max_depth: [5, 10]
    catch22:
      catch22___n_estimators: [100, 200, 300]
    tsfresh:
      tsfresh___n_estimators: [100, 200, 300]
    random_interval:
      random_interval___n_estimators: [100, 200, 300]
    CNN: {}
    CNTC: {}
    FCN: {}
    LSTMFCN: {}
    MACNN: {}
    MCDCNN: {}
    MLP: {}
    ResNet: {}
    SimpleRNN: {}
    TapNet: {}
  
    
